package Pojo;
// Generated 19/06/2015 12:59:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Camiones generated by hbm2java
 */
public class Camiones  implements java.io.Serializable {


     private Integer idCamion;
     private Rutas rutas;
     private String marca;
     private String modelo;
     private String dominio;
     private Integer anio;
     private String descripcion;
     private Set<Viajes> viajeses = new HashSet<Viajes>(0);

    public Camiones() {
    }

    public Camiones(Rutas rutas, String marca, String modelo, String dominio, Integer anio, String descripcion, Set<Viajes> viajeses) {
       this.rutas = rutas;
       this.marca = marca;
       this.modelo = modelo;
       this.dominio = dominio;
       this.anio = anio;
       this.descripcion = descripcion;
       this.viajeses = viajeses;
    }
   
    public Integer getIdCamion() {
        return this.idCamion;
    }
    
    public void setIdCamion(Integer idCamion) {
        this.idCamion = idCamion;
    }
    public Rutas getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Rutas rutas) {
        this.rutas = rutas;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getDominio() {
        return this.dominio;
    }
    
    public void setDominio(String dominio) {
        this.dominio = dominio;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Viajes> getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set<Viajes> viajeses) {
        this.viajeses = viajeses;
    }




}


