package Pojo;
// Generated 09-jul-2015 22:43:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private Sucursales sucursales;
     private String apellido;
     private String nombre;
     private Integer legajo;
     private String cargo;
     private String area;
     private Date fechaAlta;
     private Set usuarioses = new HashSet(0);
     private Set estadoses = new HashSet(0);
     private Set facturases = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(Sucursales sucursales, String apellido, String nombre) {
        this.sucursales = sucursales;
        this.apellido = apellido;
        this.nombre = nombre;
    }
    public Empleados(Sucursales sucursales, String apellido, String nombre, Integer legajo, String cargo, String area, Date fechaAlta, Set usuarioses, Set estadoses, Set facturases) {
       this.sucursales = sucursales;
       this.apellido = apellido;
       this.nombre = nombre;
       this.legajo = legajo;
       this.cargo = cargo;
       this.area = area;
       this.fechaAlta = fechaAlta;
       this.usuarioses = usuarioses;
       this.estadoses = estadoses;
       this.facturases = facturases;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(Integer legajo) {
        this.legajo = legajo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getEstadoses() {
        return this.estadoses;
    }
    
    public void setEstadoses(Set estadoses) {
        this.estadoses = estadoses;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


