package Pojo;
// Generated 09-jul-2015 22:30:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private Integer idEstado;
     private Empleados empleados;
     private Paquetes paquetes;
     private Sucursales sucursales;
     private String descripcion;
     private Date fecha;

    public Estados() {
    }

	
    public Estados(Paquetes paquetes, String descripcion) {
        this.paquetes = paquetes;
        this.descripcion = descripcion;
    }
    public Estados(Empleados empleados, Paquetes paquetes, Sucursales sucursales, String descripcion, Date fecha) {
       this.empleados = empleados;
       this.paquetes = paquetes;
       this.sucursales = sucursales;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


