package Pojo;
// Generated 09-jul-2015 22:43:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidades generated by hbm2java
 */
public class Localidades  implements java.io.Serializable {


     private Integer idLocalidad;
     private Provincias provincias;
     private String nombre;
     private Set sucursaleses = new HashSet(0);

    public Localidades() {
    }

	
    public Localidades(Provincias provincias, String nombre) {
        this.provincias = provincias;
        this.nombre = nombre;
    }
    public Localidades(Provincias provincias, String nombre, Set sucursaleses) {
       this.provincias = provincias;
       this.nombre = nombre;
       this.sucursaleses = sucursaleses;
    }
   
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }




}


