package Pojo;
// Generated 19/06/2015 12:59:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private Integer idPais;
     private String nombre;
     private Set<Provincias> provinciases = new HashSet<Provincias>(0);

    public Paises() {
    }

	
    public Paises(String nombre) {
        this.nombre = nombre;
    }
    public Paises(String nombre, Set<Provincias> provinciases) {
       this.nombre = nombre;
       this.provinciases = provinciases;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Provincias> getProvinciases() {
        return this.provinciases;
    }
    
    public void setProvinciases(Set<Provincias> provinciases) {
        this.provinciases = provinciases;
    }




}


