package Pojo;
// Generated 09-jul-2015 22:30:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paquetes generated by hbm2java
 */
public class Paquetes  implements java.io.Serializable {


     private Integer idPaquete;
     private Clientes clientes;
     private Facturas facturas;
     private Servicios servicios;
     private Sucursales sucursalesByOrigen;
     private Sucursales sucursalesByDestino;
     private Float peso;
     private Float costoTotal;
     private String destinatarioNombre;
     private int destinatarioDni;
     private String destinatarioDireccion;
     private String destinatarioTelefono;
     private String destinatarioEmail;
     private Set estadoses = new HashSet(0);
     private Set viajeses = new HashSet(0);

    public Paquetes() {
    }

	
    public Paquetes(Sucursales sucursalesByOrigen, Sucursales sucursalesByDestino, String destinatarioNombre, int destinatarioDni) {
        this.sucursalesByOrigen = sucursalesByOrigen;
        this.sucursalesByDestino = sucursalesByDestino;
        this.destinatarioNombre = destinatarioNombre;
        this.destinatarioDni = destinatarioDni;
    }
    public Paquetes(Clientes clientes, Facturas facturas, Servicios servicios, Sucursales sucursalesByOrigen, Sucursales sucursalesByDestino, Float peso, Float costoTotal, String destinatarioNombre, int destinatarioDni, String destinatarioDireccion, String destinatarioTelefono, String destinatarioEmail, Set estadoses, Set viajeses) {
       this.clientes = clientes;
       this.facturas = facturas;
       this.servicios = servicios;
       this.sucursalesByOrigen = sucursalesByOrigen;
       this.sucursalesByDestino = sucursalesByDestino;
       this.peso = peso;
       this.costoTotal = costoTotal;
       this.destinatarioNombre = destinatarioNombre;
       this.destinatarioDni = destinatarioDni;
       this.destinatarioDireccion = destinatarioDireccion;
       this.destinatarioTelefono = destinatarioTelefono;
       this.destinatarioEmail = destinatarioEmail;
       this.estadoses = estadoses;
       this.viajeses = viajeses;
    }
   
    public Integer getIdPaquete() {
        return this.idPaquete;
    }
    
    public void setIdPaquete(Integer idPaquete) {
        this.idPaquete = idPaquete;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Sucursales getSucursalesByOrigen() {
        return this.sucursalesByOrigen;
    }
    
    public void setSucursalesByOrigen(Sucursales sucursalesByOrigen) {
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public Sucursales getSucursalesByDestino() {
        return this.sucursalesByDestino;
    }
    
    public void setSucursalesByDestino(Sucursales sucursalesByDestino) {
        this.sucursalesByDestino = sucursalesByDestino;
    }
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public Float getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(Float costoTotal) {
        this.costoTotal = costoTotal;
    }
    public String getDestinatarioNombre() {
        return this.destinatarioNombre;
    }
    
    public void setDestinatarioNombre(String destinatarioNombre) {
        this.destinatarioNombre = destinatarioNombre;
    }
    public int getDestinatarioDni() {
        return this.destinatarioDni;
    }
    
    public void setDestinatarioDni(int destinatarioDni) {
        this.destinatarioDni = destinatarioDni;
    }
    public String getDestinatarioDireccion() {
        return this.destinatarioDireccion;
    }
    
    public void setDestinatarioDireccion(String destinatarioDireccion) {
        this.destinatarioDireccion = destinatarioDireccion;
    }
    public String getDestinatarioTelefono() {
        return this.destinatarioTelefono;
    }
    
    public void setDestinatarioTelefono(String destinatarioTelefono) {
        this.destinatarioTelefono = destinatarioTelefono;
    }
    public String getDestinatarioEmail() {
        return this.destinatarioEmail;
    }
    
    public void setDestinatarioEmail(String destinatarioEmail) {
        this.destinatarioEmail = destinatarioEmail;
    }
    public Set getEstadoses() {
        return this.estadoses;
    }
    
    public void setEstadoses(Set estadoses) {
        this.estadoses = estadoses;
    }
    public Set getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set viajeses) {
        this.viajeses = viajeses;
    }




}


