package Pojo;
// Generated 19/06/2015 12:59:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rutas generated by hbm2java
 */
public class Rutas  implements java.io.Serializable {


     private Integer idRuta;
     private Sucursales sucursalesByDestino;
     private Sucursales sucursalesByOrigen;
     private String descripcion;
     private Integer cantidadSucursales;
     private Set<Camiones> camioneses = new HashSet<Camiones>(0);
     private Set<Sucursalesxruta> sucursalesxrutas = new HashSet<Sucursalesxruta>(0);

    public Rutas() {
    }

	
    public Rutas(Sucursales sucursalesByDestino, Sucursales sucursalesByOrigen) {
        this.sucursalesByDestino = sucursalesByDestino;
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public Rutas(Sucursales sucursalesByDestino, Sucursales sucursalesByOrigen, String descripcion, Integer cantidadSucursales, Set<Camiones> camioneses, Set<Sucursalesxruta> sucursalesxrutas) {
       this.sucursalesByDestino = sucursalesByDestino;
       this.sucursalesByOrigen = sucursalesByOrigen;
       this.descripcion = descripcion;
       this.cantidadSucursales = cantidadSucursales;
       this.camioneses = camioneses;
       this.sucursalesxrutas = sucursalesxrutas;
    }
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }
    public Sucursales getSucursalesByDestino() {
        return this.sucursalesByDestino;
    }
    
    public void setSucursalesByDestino(Sucursales sucursalesByDestino) {
        this.sucursalesByDestino = sucursalesByDestino;
    }
    public Sucursales getSucursalesByOrigen() {
        return this.sucursalesByOrigen;
    }
    
    public void setSucursalesByOrigen(Sucursales sucursalesByOrigen) {
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCantidadSucursales() {
        return this.cantidadSucursales;
    }
    
    public void setCantidadSucursales(Integer cantidadSucursales) {
        this.cantidadSucursales = cantidadSucursales;
    }
    public Set<Camiones> getCamioneses() {
        return this.camioneses;
    }
    
    public void setCamioneses(Set<Camiones> camioneses) {
        this.camioneses = camioneses;
    }
    public Set<Sucursalesxruta> getSucursalesxrutas() {
        return this.sucursalesxrutas;
    }
    
    public void setSucursalesxrutas(Set<Sucursalesxruta> sucursalesxrutas) {
        this.sucursalesxrutas = sucursalesxrutas;
    }




}


