package Pojo;
// Generated 09-jul-2015 22:43:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private Integer idServicio;
     private String nombre;
     private String descripcion;
     private Float costokg;
     private Float costoseguro;
     private Float montoasegurado;
     private Set paqueteses = new HashSet(0);

    public Servicios() {
    }

    public Servicios(String nombre, String descripcion, Float costokg, Float costoseguro, Float montoasegurado, Set paqueteses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costokg = costokg;
       this.costoseguro = costoseguro;
       this.montoasegurado = montoasegurado;
       this.paqueteses = paqueteses;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getCostokg() {
        return this.costokg;
    }
    
    public void setCostokg(Float costokg) {
        this.costokg = costokg;
    }
    public Float getCostoseguro() {
        return this.costoseguro;
    }
    
    public void setCostoseguro(Float costoseguro) {
        this.costoseguro = costoseguro;
    }
    public Float getMontoasegurado() {
        return this.montoasegurado;
    }
    
    public void setMontoasegurado(Float montoasegurado) {
        this.montoasegurado = montoasegurado;
    }
    public Set getPaqueteses() {
        return this.paqueteses;
    }
    
    public void setPaqueteses(Set paqueteses) {
        this.paqueteses = paqueteses;
    }




}


