package Pojo;
// Generated 09-jul-2015 22:30:32 by Hibernate Tools 4.3.1



/**
 * Sucursalesxruta generated by hbm2java
 */
public class Sucursalesxruta  implements java.io.Serializable {


     private Integer idSucursalesxRuta;
     private Rutas rutas;
     private Sucursales sucursalesByOrigen;
     private Sucursales sucursalesByDestino;
     private Integer secuencia;

    public Sucursalesxruta() {
    }

	
    public Sucursalesxruta(Rutas rutas, Sucursales sucursalesByOrigen, Sucursales sucursalesByDestino) {
        this.rutas = rutas;
        this.sucursalesByOrigen = sucursalesByOrigen;
        this.sucursalesByDestino = sucursalesByDestino;
    }
    public Sucursalesxruta(Rutas rutas, Sucursales sucursalesByOrigen, Sucursales sucursalesByDestino, Integer secuencia) {
       this.rutas = rutas;
       this.sucursalesByOrigen = sucursalesByOrigen;
       this.sucursalesByDestino = sucursalesByDestino;
       this.secuencia = secuencia;
    }
   
    public Integer getIdSucursalesxRuta() {
        return this.idSucursalesxRuta;
    }
    
    public void setIdSucursalesxRuta(Integer idSucursalesxRuta) {
        this.idSucursalesxRuta = idSucursalesxRuta;
    }
    public Rutas getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Rutas rutas) {
        this.rutas = rutas;
    }
    public Sucursales getSucursalesByOrigen() {
        return this.sucursalesByOrigen;
    }
    
    public void setSucursalesByOrigen(Sucursales sucursalesByOrigen) {
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public Sucursales getSucursalesByDestino() {
        return this.sucursalesByDestino;
    }
    
    public void setSucursalesByDestino(Sucursales sucursalesByDestino) {
        this.sucursalesByDestino = sucursalesByDestino;
    }
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }




}


