package Pojo;
// Generated 09-jul-2015 22:30:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Integer idSucursal;
     private Localidades localidades;
     private String direccion;
     private String horario;
     private String descripcion;
     private Set estadoses = new HashSet(0);
     private Set viajesesForDestino = new HashSet(0);
     private Set sucursalesxrutasForOrigen = new HashSet(0);
     private Set paquetesesForOrigen = new HashSet(0);
     private Set viajesesForOrigen = new HashSet(0);
     private Set sucursalesxrutasForDestino = new HashSet(0);
     private Set empleadoses = new HashSet(0);
     private Set rutasesForOrigen = new HashSet(0);
     private Set gerenteses = new HashSet(0);
     private Set rutasesForDestino = new HashSet(0);
     private Set paquetesesForDestino = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(Localidades localidades) {
        this.localidades = localidades;
    }
    public Sucursales(Localidades localidades, String direccion, String horario, String descripcion, Set estadoses, Set viajesesForDestino, Set sucursalesxrutasForOrigen, Set paquetesesForOrigen, Set viajesesForOrigen, Set sucursalesxrutasForDestino, Set empleadoses, Set rutasesForOrigen, Set gerenteses, Set rutasesForDestino, Set paquetesesForDestino) {
       this.localidades = localidades;
       this.direccion = direccion;
       this.horario = horario;
       this.descripcion = descripcion;
       this.estadoses = estadoses;
       this.viajesesForDestino = viajesesForDestino;
       this.sucursalesxrutasForOrigen = sucursalesxrutasForOrigen;
       this.paquetesesForOrigen = paquetesesForOrigen;
       this.viajesesForOrigen = viajesesForOrigen;
       this.sucursalesxrutasForDestino = sucursalesxrutasForDestino;
       this.empleadoses = empleadoses;
       this.rutasesForOrigen = rutasesForOrigen;
       this.gerenteses = gerenteses;
       this.rutasesForDestino = rutasesForDestino;
       this.paquetesesForDestino = paquetesesForDestino;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEstadoses() {
        return this.estadoses;
    }
    
    public void setEstadoses(Set estadoses) {
        this.estadoses = estadoses;
    }
    public Set getViajesesForDestino() {
        return this.viajesesForDestino;
    }
    
    public void setViajesesForDestino(Set viajesesForDestino) {
        this.viajesesForDestino = viajesesForDestino;
    }
    public Set getSucursalesxrutasForOrigen() {
        return this.sucursalesxrutasForOrigen;
    }
    
    public void setSucursalesxrutasForOrigen(Set sucursalesxrutasForOrigen) {
        this.sucursalesxrutasForOrigen = sucursalesxrutasForOrigen;
    }
    public Set getPaquetesesForOrigen() {
        return this.paquetesesForOrigen;
    }
    
    public void setPaquetesesForOrigen(Set paquetesesForOrigen) {
        this.paquetesesForOrigen = paquetesesForOrigen;
    }
    public Set getViajesesForOrigen() {
        return this.viajesesForOrigen;
    }
    
    public void setViajesesForOrigen(Set viajesesForOrigen) {
        this.viajesesForOrigen = viajesesForOrigen;
    }
    public Set getSucursalesxrutasForDestino() {
        return this.sucursalesxrutasForDestino;
    }
    
    public void setSucursalesxrutasForDestino(Set sucursalesxrutasForDestino) {
        this.sucursalesxrutasForDestino = sucursalesxrutasForDestino;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }
    public Set getRutasesForOrigen() {
        return this.rutasesForOrigen;
    }
    
    public void setRutasesForOrigen(Set rutasesForOrigen) {
        this.rutasesForOrigen = rutasesForOrigen;
    }
    public Set getGerenteses() {
        return this.gerenteses;
    }
    
    public void setGerenteses(Set gerenteses) {
        this.gerenteses = gerenteses;
    }
    public Set getRutasesForDestino() {
        return this.rutasesForDestino;
    }
    
    public void setRutasesForDestino(Set rutasesForDestino) {
        this.rutasesForDestino = rutasesForDestino;
    }
    public Set getPaquetesesForDestino() {
        return this.paquetesesForDestino;
    }
    
    public void setPaquetesesForDestino(Set paquetesesForDestino) {
        this.paquetesesForDestino = paquetesesForDestino;
    }




}


