package Pojo;
// Generated 19/06/2015 12:59:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Integer idSucursal;
     private Localidades localidades;
     private String direccion;
     private String horario;
     private String descripcion;
     private Set<Rutas> rutasesForDestino = new HashSet<Rutas>(0);
     private Set<Rutas> rutasesForOrigen = new HashSet<Rutas>(0);
     private Set<Gerentes> gerenteses = new HashSet<Gerentes>(0);
     private Set<Paquetes> paquetesesForOrigen = new HashSet<Paquetes>(0);
     private Set<Paquetes> paquetesesForDestino = new HashSet<Paquetes>(0);
     private Set<Estados> estadoses = new HashSet<Estados>(0);
     private Set<Empleados> empleadoses = new HashSet<Empleados>(0);
     private Set<Sucursalesxruta> sucursalesxrutasForDestino = new HashSet<Sucursalesxruta>(0);
     private Set<Viajes> viajesesForDestino = new HashSet<Viajes>(0);
     private Set<Sucursalesxruta> sucursalesxrutasForOrigen = new HashSet<Sucursalesxruta>(0);
     private Set<Viajes> viajesesForOrigen = new HashSet<Viajes>(0);

    public Sucursales() {
    }

	
    public Sucursales(Localidades localidades) {
        this.localidades = localidades;
    }
    public Sucursales(Localidades localidades, String direccion, String horario, String descripcion, Set<Rutas> rutasesForDestino, Set<Rutas> rutasesForOrigen, Set<Gerentes> gerenteses, Set<Paquetes> paquetesesForOrigen, Set<Paquetes> paquetesesForDestino, Set<Estados> estadoses, Set<Empleados> empleadoses, Set<Sucursalesxruta> sucursalesxrutasForDestino, Set<Viajes> viajesesForDestino, Set<Sucursalesxruta> sucursalesxrutasForOrigen, Set<Viajes> viajesesForOrigen) {
       this.localidades = localidades;
       this.direccion = direccion;
       this.horario = horario;
       this.descripcion = descripcion;
       this.rutasesForDestino = rutasesForDestino;
       this.rutasesForOrigen = rutasesForOrigen;
       this.gerenteses = gerenteses;
       this.paquetesesForOrigen = paquetesesForOrigen;
       this.paquetesesForDestino = paquetesesForDestino;
       this.estadoses = estadoses;
       this.empleadoses = empleadoses;
       this.sucursalesxrutasForDestino = sucursalesxrutasForDestino;
       this.viajesesForDestino = viajesesForDestino;
       this.sucursalesxrutasForOrigen = sucursalesxrutasForOrigen;
       this.viajesesForOrigen = viajesesForOrigen;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Rutas> getRutasesForDestino() {
        return this.rutasesForDestino;
    }
    
    public void setRutasesForDestino(Set<Rutas> rutasesForDestino) {
        this.rutasesForDestino = rutasesForDestino;
    }
    public Set<Rutas> getRutasesForOrigen() {
        return this.rutasesForOrigen;
    }
    
    public void setRutasesForOrigen(Set<Rutas> rutasesForOrigen) {
        this.rutasesForOrigen = rutasesForOrigen;
    }
    public Set<Gerentes> getGerenteses() {
        return this.gerenteses;
    }
    
    public void setGerenteses(Set<Gerentes> gerenteses) {
        this.gerenteses = gerenteses;
    }
    public Set<Paquetes> getPaquetesesForOrigen() {
        return this.paquetesesForOrigen;
    }
    
    public void setPaquetesesForOrigen(Set<Paquetes> paquetesesForOrigen) {
        this.paquetesesForOrigen = paquetesesForOrigen;
    }
    public Set<Paquetes> getPaquetesesForDestino() {
        return this.paquetesesForDestino;
    }
    
    public void setPaquetesesForDestino(Set<Paquetes> paquetesesForDestino) {
        this.paquetesesForDestino = paquetesesForDestino;
    }
    public Set<Estados> getEstadoses() {
        return this.estadoses;
    }
    
    public void setEstadoses(Set<Estados> estadoses) {
        this.estadoses = estadoses;
    }
    public Set<Empleados> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleados> empleadoses) {
        this.empleadoses = empleadoses;
    }
    public Set<Sucursalesxruta> getSucursalesxrutasForDestino() {
        return this.sucursalesxrutasForDestino;
    }
    
    public void setSucursalesxrutasForDestino(Set<Sucursalesxruta> sucursalesxrutasForDestino) {
        this.sucursalesxrutasForDestino = sucursalesxrutasForDestino;
    }
    public Set<Viajes> getViajesesForDestino() {
        return this.viajesesForDestino;
    }
    
    public void setViajesesForDestino(Set<Viajes> viajesesForDestino) {
        this.viajesesForDestino = viajesesForDestino;
    }
    public Set<Sucursalesxruta> getSucursalesxrutasForOrigen() {
        return this.sucursalesxrutasForOrigen;
    }
    
    public void setSucursalesxrutasForOrigen(Set<Sucursalesxruta> sucursalesxrutasForOrigen) {
        this.sucursalesxrutasForOrigen = sucursalesxrutasForOrigen;
    }
    public Set<Viajes> getViajesesForOrigen() {
        return this.viajesesForOrigen;
    }
    
    public void setViajesesForOrigen(Set<Viajes> viajesesForOrigen) {
        this.viajesesForOrigen = viajesesForOrigen;
    }




}


