package Pojo;
// Generated 09-jul-2015 22:30:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private Integer idViaje;
     private Camiones camiones;
     private Sucursales sucursalesByDestino;
     private Sucursales sucursalesByOrigen;
     private Date fechaSalida;
     private Date fechaLlegada;
     private String horaSalida;
     private String horaLlegada;
     private Set paqueteses = new HashSet(0);

    public Viajes() {
    }

	
    public Viajes(Camiones camiones, Sucursales sucursalesByDestino, Sucursales sucursalesByOrigen) {
        this.camiones = camiones;
        this.sucursalesByDestino = sucursalesByDestino;
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public Viajes(Camiones camiones, Sucursales sucursalesByDestino, Sucursales sucursalesByOrigen, Date fechaSalida, Date fechaLlegada, String horaSalida, String horaLlegada, Set paqueteses) {
       this.camiones = camiones;
       this.sucursalesByDestino = sucursalesByDestino;
       this.sucursalesByOrigen = sucursalesByOrigen;
       this.fechaSalida = fechaSalida;
       this.fechaLlegada = fechaLlegada;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.paqueteses = paqueteses;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public Camiones getCamiones() {
        return this.camiones;
    }
    
    public void setCamiones(Camiones camiones) {
        this.camiones = camiones;
    }
    public Sucursales getSucursalesByDestino() {
        return this.sucursalesByDestino;
    }
    
    public void setSucursalesByDestino(Sucursales sucursalesByDestino) {
        this.sucursalesByDestino = sucursalesByDestino;
    }
    public Sucursales getSucursalesByOrigen() {
        return this.sucursalesByOrigen;
    }
    
    public void setSucursalesByOrigen(Sucursales sucursalesByOrigen) {
        this.sucursalesByOrigen = sucursalesByOrigen;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }
    public String getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(String horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public Set getPaqueteses() {
        return this.paqueteses;
    }
    
    public void setPaqueteses(Set paqueteses) {
        this.paqueteses = paqueteses;
    }




}


